services:
  database:
    container_name: cashflow-database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cashflow
      POSTGRES_PASSWORD: cashflow

  keycloak:
    container_name: cashflow-keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev