spring:
  application:
    name: Cashflow
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cashflow}
    username: ${DATABASE_USERNAME:cashflow}
    password: ${DATABASE_PASSWORD:cashflow}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/cashflow/protocol/openid-connect/certs
keycloak:
  auth-server-url: http://localhost:8090
  realm: cashflow
  docker:
    compose:
      lifecycle-management: start_only

server:
  port: 8080

springdoc:
  oauth2:
    auth-url: http://localhost:8090/realms/cashflow/protocol/openid-connect/auth
    token-url: http://localhost:8090/realms/cashflow/protocol/openid-connect/token
  swagger-ui:
    oauth:
      client-id: cashflow-core
      client-secret: secret
      use-pkce-with-authorization-code-grant: true
